# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20171130_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stopwords_word', models.CharField(max_length=50)),
            ],
        ),
    ]
