# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20171201_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='classifier_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
