# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20171202_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopwords',
            name='classifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Classifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classifier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
