# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classy', '0008_album_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier_name', models.CharField(max_length=100)),
                ('classifier_logo', models.FileField(upload_to='')),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_title', models.CharField(max_length=100)),
                ('corpus_text', models.TextField()),
                ('corpus_label', models.CharField(max_length=100)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Classifier')),
            ],
        ),
    ]
